services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://avnadmin:AVNS_xG4U1d5QynJ4QiLALuf@event-management-db-virtualwindow-10b3.i.aivencloud.com:26999/defaultdb?sslmode=require
      - JWT_SECRET=my-secret-12345
      - PORT=5000
      - DB_HOST=event-management-db-virtualwindow-10b3.i.aivencloud.com
      - DB_PORT=26999
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_xG4U1d5QynJ4QiLALuf
      - DB_NAME=defaultdb
      - DB_SSL_CA=/app/aiven-ca-cert.pem
    volumes:
      - ./aiven-ca-cert.pem:/app/aiven-ca-cert.pem
    restart: unless-stopped